### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by TimSirmovics** [serilog-contrib/serilog-ui#1]
First of all thanks for creating this project, it is exactly what I was looking for.

A couple of small issues I noticed:
1. As I am testing Serilog, my log table only contains 12 entries but the paging of the viewer does not work. It shows 5 pages, and as I click on each page it says for example "Showing 10 to 20 of 12 entries" but it shows entries 2- 11. On page 5 it says "Showing 40 to 50 of 12 entries" but shows entries 1 - 8.
2. The properties view does not work in Firefox / IE, only in Chrome.
3. Not sure if this is intentional but the main NuGet package is called Serilog.UI, but the provider package names start with Serilog.Ui (different casing).

Are you happy to accept pull requests to this project? I would like to add in custom column support and property searching at some stage.

**Comment by mo-esmp** [comment]
Thank you @TimSirmovics for reporting these issues. I started writing this library when I was in quarantine, and I was infected with the coronavirus and didn't have good concentration.

1. I'm aware of the malfunctioning of paging. I was planning for the next version to migrate UI from Razor to React but it needs lots of effort and now I'm quite busy and for now, it's better to fix paging bugs.
2. I haven't tested properties view in different browsers and it doesn't work for PostgreSQL provider either
3. I follow `Pascal Casing` convention for naming even for abbreviation, so `Serilog.Ui` is correct. I should fix naming for the next version.

You are welcome to contribute and of course, pull requests will be accepted.

**Comment by mo-esmp** [comment]
The issues that you were addressed, fixed in version 2.
