### ISSUE TITLE
Deployed to developent, UI popup "You are not authorized to access logs"

### ISSUE THREAD

**Issue by bc3** [serilog-contrib/serilog-ui#100]
**Describe the bug**
When we deploy our code to development and we go to serlog-ui, we get this popup: "You are not authorized to access logs"

**To Reproduce**
1. /serilog-ui/index.html

**Expected behavior**
The grid with logs is shown instead of a popup

**Screenshots**
![image](https://github.com/serilog-contrib/serilog-ui/assets/2547576/f520cf2c-c513-4263-bd7a-b974767efadc)

**Desktop (please complete the following information):**
 - OS: MacOs but app is deployed to K8S
 - Browser Chrome

**Comment by mo-esmp** [comment]
By default, Serilog UI allows access to the log page only for local requests. To give appropriate rights  after deployment, you need to configure authorization.
Please check the [Authorization configuration section](https://github.com/serilog-contrib/serilog-ui/wiki/Install:-Configuration-Options#authorization).

**Comment by mo-esmp** [comment]
Feel free to re-open the issue if it is still not resolved.
