### ISSUE TITLE
Error Message column does not exist

### ISSUE THREAD

**Issue by drlowery** [serilog-contrib/serilog-ui#104]
Using Postgresql provider I get the error message:

 "errorMessage": "{\"errorMessage\":\"42703: column \\\"message\\\" does not exist\\r\\n\\r\\nPOSITION: 8\"}"
 
 The column does exist in the table.
 
 .net core 7, web api project
 serilog.sinks.postgresql.alternative 4.0.2 
serilog.ui.postgresqlprovider 2.2.2 
 
 table schema
 CREATE TABLE IF NOT EXISTS "Logs" (
    "Message" TEXT,
    "MessageTemplate" TEXT,
    "Level" INTEGER,
    "Timestamp" TIMESTAMP WITH TIME ZONE,
    "Exception" TEXT,
    "LogEvent" JSONB
) USING HEAP;

builder.Services.AddSerilogUi(options =>
{
    options.UseNpgSql(dbSettings["ConnectionString"], "Logs", "public");
});

What am I missing?

Thanks!

**Comment by mo-esmp** [comment]
Thanks for reporting the issue. The current PostgreSQL data provider is based on the [serilog-sinks-postgresql](https://github.com/b00ted/serilog-sinks-postgresql/blob/master/Serilog.Sinks.PostgreSQL/Sinks/PostgreSQL/ColumnOptions.cs) sink and we need to introduce a new package for `serilog.sinks.postgresql.alternative` sink because they use a different table schema for saving logs.

**Comment by drlowery** [comment]
AH thanks, had to use the alternative for another issue.
Thanks again for the quick answer.
Will keep a on the look out for the support to alterative

**Comment by drlowery** [comment]
to help others I got this to work with serilog.sinks.postgresql.alternative

Add column writer definitions

 IDictionary<string, ColumnWriterBase> columnWriters = new Dictionary<string, ColumnWriterBase>
 {
     {"message", new RenderedMessageColumnWriter(NpgsqlDbType.Text) },
     {"message_template", new MessageTemplateColumnWriter(NpgsqlDbType.Text) },
     {"level", new LevelColumnWriter(false, NpgsqlDbType.Integer) },
     {"timestamp", new TimestampColumnWriter(NpgsqlDbType.Timestamp) },
     {"exception", new ExceptionColumnWriter(NpgsqlDbType.Text) },
     {"log_event", new LogEventSerializedColumnWriter(NpgsqlDbType.Jsonb) }
 };

the configure with the writers

                loggerConfiguration.WriteTo.PostgreSQL(
                    dbSettings["ConnectionString"] ?? "",
                    tableName: "logs",
                    columnWriters,
                    needAutoCreateTable: true,
                    schemaName: "public");

Then the normal usage of serilog-ui will work fine.
It matches the lower-case of the column names and schema

**Comment by mo-esmp** [comment]
Please upgrade `Serilog.UI.PostgreSqlProvider` nuget package to version `2.3.0`.
