### ISSUE TITLE
About search and authorization,some advices

### ISSUE THREAD

**Issue by 0x-newe** [serilog-contrib/serilog-ui#11]
Hello boss,Currently using Serilog.UI.MongoDbProviderr
1.Search by date, can it be accurate to the second?
2.Search message ,Can you support Chinese search?
3.You can add username and password to authorize when authorizing, and the experience will be better.

The above three points are some of the problems that I encounter in my daily life. I hope that the boss will make changes. Thank you very much.

**Comment by mo-esmp** [comment]
Hey @linewwei 
1. Unfortunately, the date filter does not support HH:mm:ss and it supports day only, I need to add that and also you are very welcome to contribute and add this feature.
2. I guess it should work fine with the Chinese language it logs messages contain Chinese characters but I haven't tested that.
3. If your authorization mechanism uses the cookie, you need only to login via your application login page and the login cookie will be sent to the server and you will be authorized and no other action is required. For the JWT token, you can enter the token just like swagger and the token will be passed to the server for each request. If you have any other scenarios for authorization please let me know.

**Comment by 0x-newe** [comment]
> Hey @linewwei
> 
> 1. Unfortunately, the date filter does not support HH:mm:ss and it supports day only, I need to add that and also you are very welcome to contribute and add this feature.
> 2. I guess it should work fine with the Chinese language it logs messages contain Chinese characters but I haven't tested that.
> 3. If your authorization mechanism uses the cookie, you need only to login via your application login page and the login cookie will be sent to the server and you will be authorized and no other action is required. For the JWT token, you can enter the token just like swagger and the token will be passed to the server for each request. If you have any other scenarios for authorization please let me know.

thank you for your reply,In response to question 2, I modified your source code as shown below to support Chinese search through HttpUtility.UrlDecode
![image](https://user-images.githubusercontent.com/3862575/128030654-b3104298-0aba-420e-adb8-3f7b3b5a16c1.png)
Question 1 Support time to search in seconds, I can provide you with some UI reference, the earliest I used this person's open source serilog dashboard framework connection is https://github.com/realLiangshiwei/LogDashboard You can refer to it, it is Chinese An open source project, but it is not perfect enough. The UI and authorization of his project are relatively simple and easy to use. It is provided to you and see if you can learn from it.

**Comment by 0x-newe** [comment]
I did not continue to use this project https://github.com/realLiangshiwei/LogDashboard because it did not adapt to more data sources. Your project data sources are more adapted and more complete. Your project and LogDashboard are this I think the project will be more perfect when integrated. Of course, this is just some of my personal suggestions. I personally feel that the UI of this https://github.com/stisla/stisla project will be more beautiful, and various UI components are more suitable. It is equipped with a mobile terminal and can be combined freely. Can you please refer to it?
![image](https://user-images.githubusercontent.com/3862575/128032703-2c469dee-c325-4988-a34d-856131a8b680.png)

**Comment by mo-esmp** [comment]
Thank you for your suggestion, I will check them as soon as I can.
