### ISSUE TITLE
Any support for ColumnOptions?

### ISSUE THREAD

**Issue by shahabfar** [serilog-contrib/serilog-ui#112]
As I'm using some additional columns in my log table I wanna know if are you supporting these kinds of column options.
If not can you recommend any workaround to display additional columns in the UI grid?

**Comment by mo-esmp** [comment]
Unfortunately, Serilog UI does not support additional columns yet, and currently there is no way to display additional columns in the UI. I will start investing in implementing additional columns.

**Comment by followynne** [comment]
Hello @shahabfar

Currently I'm working on the new UI frontend. after the first stable version is out I'll try to make something about additional columns, I have an idea but first I need to complete the base 🙂

**Comment by followynne** [comment]
Hello @shahabfar 

additional columns support is now live in v3. 😄
