### ISSUE TITLE
[feat] Auto-expand dropdowns option when opening 'Additional Columns' modal

### ISSUE THREAD

**Issue by sommmen** [serilog-contrib/serilog-ui#129]
When clicking the 'Additional Columns' button the following modal pops up;

![image](https://github.com/user-attachments/assets/86d9728b-a647-48e9-873d-d087a1da7ebc)

Could this also be auto expanded? If i have to view a lot of logs for a property clicking the dropdown every time becomes a bit cumbersome.

**Comment by sommmen** [comment]
Also; should the wording not be more in line with serilog? so this should be 'Properties' instead of 'Additional columns'?

**Comment by followynne** [comment]
@sommmen 

good feature idea! 💯 

I'll try to implement a new UI option for auto-expand + I'll find a better wording for the modal title, which slipped off my mind during the first development ;)

**Comment by followynne** [comment]
Released in v3.0.1.
