### ISSUE TITLE
MySqlProvider is using LogLevel instead of Level. Error Unknown column LogLevel in fieldlist.

### ISSUE THREAD

**Issue by sesa507703** [serilog-contrib/serilog-ui#13]
SELECT Id, Message, LogLevel AS `Level`, TimeStamp, Exception, Properties From

must be

SELECT Id, Message, Level, TimeStamp, Exception, Properties From

**Comment by mo-esmp** [comment]
Could you please tell me which MySqlProvider you are using?
My implementation works based on [TeleSoftas/serilog-sinks-mariadb](https://github.com/TeleSoftas/serilog-sinks-mariadb).

**Comment by sesa507703** [comment]
I could only find the nuget package. 
https://www.nuget.org/packages/Serilog.Sinks.MySQL.NetCore2/2.7.5?_src=template
I will switch to TeleSoftas/serilog-sinks-mariadb. 

Thank you. Its a great package. Keep up the good work.
