### ISSUE TITLE
Opening exception details tries to parse the field as XML rather than string for MSSQL

### ISSUE THREAD

**Issue by sommmen** [serilog-contrib/serilog-ui#130]
I'm seeing the following issue when opening exception details;

![image](https://github.com/user-attachments/assets/f12a4565-941c-40dd-8100-5c7db8620a21)

This is odd, the 'exception' detail field should be a plain string.

Sample FetchLogs;

``` json
{
    "logs": [
        {
            "rowNo": 1,
            "level": "Error",
            "message": "Exception whilst [REDACTED]",
            "timestamp": "2024-08-12T00:10:57Z",
            "propertyType": "xml",
            "exception": "Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \\\u0026. Path \u0027base.originalUpload\u0027, line 1, position 75325.\r\n   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)\r\n   at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)\r\n   at [REDACTED] in C:\\agent\\_work\\3\\s\\[REDACTED].cs:line 27\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at [REDACTED] in C:\\agent\\_work\\3\\s\\[REDACTED].cs:line 1919",
            "properties": "\u003Cproperties\u003E\u003Cproperty key=\u0027OrderNumber\u0027\u003E10612ES\u003C/property\u003E\u003Cproperty key=\u0027SourceContext\u0027\u003E[REDACTED]\u003C/property\u003E\u003Cproperty key=\u0027OrderLineExternalId\u0027\u003E682632\u003C/property\u003E\u003Cproperty key=\u0027OrderExternalId\u0027\u003E809812\u003C/property\u003E\u003Cproperty key=\u0027DomainShortName\u0027\u003EES\u003C/property\u003E\u003Cproperty key=\u0027JobId\u0027\u003E63194\u003C/property\u003E\u003Cproperty key=\u0027CreatedAt\u0027\u003E08/11/2024 20:03:59\u003C/property\u003E\u003C/properties\u003E"
        }
    ],
    "total": 140499,
    "count": 1,
    "currentPage": 1
}
```

**Comment by followynne** [comment]
@sommmen 

Can you kindly provide me additional context?

As you see, the property type is XML in the sample, thus the Provider you're using expect the data serialization as XML (I guess you're using the MSSQL Provider :D)

Please let me know

- provider you use
- the sink configuration (if possible)
- any useful additional info, if possible

Addendum: I'll also change the implementation to simply print out the string data, if code parsing fails 👍

**Comment by sommmen** [comment]
> @sommmen
> 
> Can you kindly provide me additional context?
> 
> As you see, the property type is XML in the sample, thus the Provider you're using expect the data serialization as XML (I guess you're using the MSSQL Provider :D)
> 
> Please let me know
> 
>     * provider you use
> 
>     * the sink configuration (if possible)
> 
>     * any useful additional info, if possible
> 
> 
> Addendum: I'll also change the implementation to simply print out the string data, if code parsing fails 👍

<s>"As you see, the property type is XML in the sample"
I'm confused, the `$.logs.exception` field of the json i provided is not xml and it is a plain string field (the output of Exception.ToString()). The exception holds no xml or json. </s>
nvm, i see what you mean now `$.logs.propertyType` is `XML`. For the MSSQL sink the exception field is a plain string and not XML.

Could this be the same confusion we had in https://github.com/serilog-contrib/serilog-ui/pull/109#issuecomment-1911672461 ?
My config is pretty much the default for the serilog mssql sink.

Startup.cs
``` c#

services.AddSerilogUi(options =>
{
    options.UseSqlServer(c =>
    {
        c.WithConnectionString(_defaultConnectionString);
        c.WithSchema("AppLog");
        c.WithTable("WebApi");
        c.WithCustomProviderName("Web");
    });

    options.UseSqlServer(c =>
    {
        c.WithConnectionString(_defaultConnectionString);
        c.WithSchema("AppLog");
        c.WithTable("AuthApi");
        c.WithCustomProviderName("Auth");
    });

    options.UseSqlServer(c =>
    {
        c.WithConnectionString(_defaultConnectionString);
        c.WithSchema("AppLog");
        c.WithTable("Hangfire");
        c.WithCustomProviderName("Hangfire");
    });

    options.AddScopedSyncAuthFilter<MyUiAuthorizationFilter>();
});

...

app.UseSerilogUi(options =>
{
    options.WithHomeUrl(env.IsDevelopment() ? "http://localhost:4200" : "https://opg.systems");
    options.InjectJavascript("/serilog-ui/custom.js", injectInHead: true);
    options.WithAuthenticationType(AuthenticationType.Jwt);
});
```

Serilog config of one of the apps (there is a common appsettings.json file, hence the `:2` which just means another array entry)
``` json
"Serilog": {
  "Using:2": "Serilog.Sinks.MSSqlServer",
  "WriteTo:2": {
    "Name": "MSSqlServer",
    "Args": {
      "connectionString": "AppLogConnection",
      "sinkOptionsSection": {
        "tableName": "WebApi",
        "schemaName": "AppLog",
        "autoCreateSqlTable": true
      }
    }
  },
  "Filter": [
    {
      "Name": "ByExcluding",
      "Args": {
        "expression": "(RequestPath = '/api/maat' and (RequestMethod = 'POST' or RequestMethod = 'OPTIONS')) or RequestPath = '/api/health/ping' or StartsWith(RequestPath, '/swagger') or StartsWith(RequestPath, '/hangfire') or StartsWith(RequestPath, '/serilog-ui')"
      }
    }
  ]
}
```

**Comment by followynne** [comment]
@sommmen 

I think you're right - I'll give a try with the sample I made in the repo and try to understand how to improve this point :)

(something related: https://github.com/serilog-mssql/serilog-sinks-mssqlserver?tab=readme-ov-file#properties)

I'll notify you as soon as I have news!

**Comment by followynne** [comment]
Released in v3.0.1.

In the upcoming v3.1.0, Exception column rendering will be improved :)

**Comment by sommmen** [comment]
> Released in v3.0.1.
> 
> In the upcoming v3.1.0, Exception column rendering will be improved :)

Will that be released momentarily or after a while?

**Comment by followynne** [comment]
@sommmen

The feature is ready but I wanted to see if I can develop a second feature for v3.1, before releasing 😊

If you want to try it, I can create a v3.1 beta for UI and MSSQL provider - let me know if you want it and I'll do it later today 😁

**Comment by sommmen** [comment]
> @sommmen
> 
> The feature is ready but I wanted to see if I can develop a second feature for v3.1, before releasing 😊
> 
> If you want to try it, I can create a v3.1 beta for UI and MSSQL provider - let me know if you want it and I'll do it later today 😁

If the release will be later than Monday please publish a beta package, else I don't mind waiting. It has to do with me doing daily checkups.

**Comment by followynne** [comment]
@sommmen 

gotcha, you have UI and MSSQL v3.1.0-beta.1 to test out 😉  feel free to share feedback about it!

I prefer to take additional time for the stable release, 'cause I want to try to add the Log Database Id to the viewer in this release!

**Comment by sommmen** [comment]
> @sommmen
> 
> gotcha, you have UI and MSSQL v3.1.0-beta.1 to test out 😉 feel free to share feedback about it!
> 
> I prefer to take additional time for the stable release, 'cause I want to try to add the Log Database Id to the viewer in this release!

@followynne  thanks - this works great, thank you!
I've checked the other improvements aswell and they work great.

Only nitpick i have is that the exception info is now very dark and hard to read;
Aside from that the modal feels a bit small - it could be a little bit bigger imo.
The cursor has the blocked symbol, but that also feels a bit off.

![image](https://github.com/user-attachments/assets/124e4178-f15e-4701-ade7-1533df55d188)

**Comment by followynne** [comment]
@sommmen

Thanks for the feedback! I still have the pr open, I'll change something 😁
 the cursor is due to the copy button on the right!
