### ISSUE TITLE
Exception occur if RemoveStandardColumn = "Properties"

### ISSUE THREAD

**Issue by rickizud** [serilog-contrib/serilog-ui#131]
Exception occur if RemoveStandardColumn = "Properties"

Below is the possible root cause of this bugs:
![Untitled](https://github.com/user-attachments/assets/4a9466d6-9cbb-4859-8e75-fb4ed6e12904)

**Comment by followynne** [comment]
@rickizud

Can you provide additional context please?

The bug report is not enough :)

Please share your LogModel class implementation, if possible!

EDIT: @rickizud 
releasing a patch as soon as possible!

**Comment by rickizud** [comment]
Hi, when will the nuget package updated?

**Comment by followynne** [comment]
@rickizud

Released in v3.0.1.
