### ISSUE TITLE
Does this package support .NET framework?

### ISSUE THREAD

**Issue by a157147899** [serilog-contrib/serilog-ui#14]
Hi there,

Does this package support .NET framework? Or .Net core only?

Cheers!

**Comment by mo-esmp** [comment]
Unfortunately, it only works on the ASP.NET Core projects and does not work on ASP.NET MVC projects. If you are using ASP.NET Core and targeting .NET Framework, I haven't tested that.

**Comment by a157147899** [comment]
> Unfortunately, it only works on the ASP.NET Core projects and does not work on ASP.NET MVC projects. If you are using ASP.NET Core and targeting .NET Framework, I haven't tested that.

Thanks, hope it can support ASP.NET MVC in the future.
