### ISSUE TITLE
"Invalid column name 'Properties'." at Serilog UI Home Page, when removeStandardColumns: Properties.

### ISSUE THREAD

**Issue by rickizud** [serilog-contrib/serilog-ui#140]
**Describe the bug**
- If configure to Remove Standard Columns "Properties", Serilog.Ui.MsSqlServerProvider.GetLogsAsync causes error.
- Because GetLogsAsync Dapper/SqlMapper.Async.cs uses the LogModel columns to mapping without exclude those RemovedColumns.

**Expected behavior**
- Exclude RemovedColumns mapping when selecting from Logs table at SeriLog UI Home page.

** Exception Logs **
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Properties'.\r\n   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__195_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434\r\n   at Serilog.Ui.MsSqlServerProvider.SqlServerDataProvider`1.GetLogsAsync(FetchLogsQuery queryParams)\r\n   at Serilog.Ui.MsSqlServerProvider.SqlServerDataProvider`1.FetchDataAsync(FetchLogsQuery queryParams, CancellationToken cancellationToken)\r\n   at Serilog.Ui.Web.Endpoints.SerilogUiEndpoints.FetchLogsAsync(HttpContext httpContext)\r\n   at Serilog.Ui.Web.Endpoints.SerilogUiEndpoints.GetLogsAsync()

**Comment by followynne** [comment]
@rickizud 

can I ask you the version you're using of Serilog.UI?

**Comment by rickizud** [comment]
> @rickizud
> 
> can I ask you the version you're using of Serilog.UI?

Latest v3.0.1

**Comment by rickizud** [comment]
Are u able to load the logs at Serilog-UI Home page? If ur logs table without Properties column.

**Comment by followynne** [comment]
Hello @rickizud 

sorry for the late answer. I tried with the sample app we provide in the repository and it's working.

To correctly configure the property exclusion, please follow these [steps](https://github.com/serilog-contrib/serilog-ui/wiki/Providers-Info#steps-to-configure-additional-columns).

If you want to check an example for MSSQL, you can see [this sample](https://github.com/serilog-contrib/serilog-ui/tree/master/samples/WebApi).

Let me know if you have any other doubt, otherwise I'll close the issue!

Regards
