### ISSUE TITLE
Latest version fails to load any data

### ISSUE THREAD

**Issue by sommmen** [serilog-contrib/serilog-ui#151]
**Describe the bug**
Cannot seem to load any data into serilog-ui. I see no network calls to load the dropdown to pick a database so i think the problem is there. I'm rolling back for now.

**To Reproduce**
See setup below.

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/4cb9e1f5-2b34-4c6c-b064-af6fb6bac0a8)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version Latest

**Additional context**

Startup.cs
``` c#

services.AddSerilogUi(options =>
{
    options.UseSqlServer(c =>
    {
        c.WithConnectionString(_defaultConnectionString);
        c.WithSchema("AppLog");
        c.WithTable("WebApi");
        c.WithCustomProviderName("Web");
    });

    options.UseSqlServer(c =>
    {
        c.WithConnectionString(_defaultConnectionString);
        c.WithSchema("AppLog");
        c.WithTable("AuthApi");
        c.WithCustomProviderName("Auth");
    });

    options.UseSqlServer(c =>
    {
        c.WithConnectionString(_defaultConnectionString);
        c.WithSchema("AppLog");
        c.WithTable("Hangfire");
        c.WithCustomProviderName("Hangfire");
    });

    options.AddScopedSyncAuthFilter<MyUiAuthorizationFilter>();
});

...

app.UseSerilogUi(options =>
{
    options.WithHomeUrl(env.IsDevelopment() ? "http://localhost:4200" : "https://opg.systems");
    options.InjectJavascript("/serilog-ui/custom.js", injectInHead: true);
    options.WithAuthenticationType(AuthenticationType.Jwt);
});
```

Serilog config of one of the apps (there is a common appsettings.json file, hence the `:2` which just means another array entry)
``` json
"Serilog": {
  "Using:2": "Serilog.Sinks.MSSqlServer",
  "WriteTo:2": {
    "Name": "MSSqlServer",
    "Args": {
      "connectionString": "AppLogConnection",
      "sinkOptionsSection": {
        "tableName": "WebApi",
        "schemaName": "AppLog",
        "autoCreateSqlTable": true
      }
    }
  },
  "Filter": [
    {
      "Name": "ByExcluding",
      "Args": {
        "expression": "(RequestPath = '/api/maat' and (RequestMethod = 'POST' or RequestMethod = 'OPTIONS')) or RequestPath = '/api/health/ping' or StartsWith(RequestPath, '/swagger') or StartsWith(RequestPath, '/hangfire') or StartsWith(RequestPath, '/serilog-ui')"
      }
    }
  ]
}
```

**Comment by mo-esmp** [comment]
I tested the latest version using the `SampleWebApi` project and it works fine, but based on your screenshot, you forgot to select a table!

![image](https://github.com/user-attachments/assets/0a76fdda-b239-4471-b6c3-42a1aa1466de)

**Comment by sommmen** [comment]
> I tested the latest version using the `SampleWebApi` project and it works fine, but based on your screenshot, you forgot to select a table!
> 
> ![image](https://private-user-images.githubusercontent.com/1659032/375671723-0a76fdda-b239-4471-b6c3-42a1aa1466de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzM4NDIsIm5iZiI6MTcyODYzMzU0MiwicGF0aCI6Ii8xNjU5MDMyLzM3NTY3MTcyMy0wYTc2ZmRkYS1iMjM5LTQ0NzEtYjZjMy00MmExYWExNDY2ZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDc1OTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGJkMGI3Mjk1OWM0Yjg0ZmE0YTI2NzY4N2U4ODk4NmI4Y2ZkYzYyNjUwZjhhZmNmZmVkZmM1YjQyMThjZjE5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YrfoZKEoYzANsK1t5cZe3Tmo5NW2Ds6OXxCKyWKXZnw)

Its not selectable, so i cannot select a table - do you have multiple tabels configured?

**Comment by mo-esmp** [comment]
Yes, there is two [log tables](https://github.com/serilog-contrib/serilog-ui/blob/97afd7ddcdc9600d58a6eed5c8181045543d9c86/samples/WebApi/Extensions/ServiceCollectionExtensions.cs#L131) in the sample project.

**Comment by followynne** [comment]
@sommmen

I see you have an Authentication, you need to configure the token otherwise the api call to get the table list can't be made (well, it's under auth too ahah) 😅

**Comment by sommmen** [comment]
> @sommmen
> 
> I see you have an Authentication, you need to configure the token otherwise the api call to get the table list can't be made (well, it's under auth too ahah) 😅

I should've been auto logged in via my customs script;

``` js
/* https://stackoverflow.com/a/25346429/4122889 */
function getCookie(name) {
    function escape(s) { return s.replace(/([.*+?\^$(){}|\[\]\/\\])/g, "\\$1"); }
    var match = document.cookie.match(RegExp("(?:^|;\\s*)" + escape(name) + "=([^;]*)"));
    return match ? match[1] : null;
}

(function () {
    console.log("custom.js is loaded.");

    var token = getCookie("token");

    if (token) {
        sessionStorage.setItem("serilog_ui_jwt_bearerToken", token);
    }
})(); 
```

Could that have been broken?

**Comment by followynne** [comment]
@sommmen

It's possible, I suggest you re-check the script - if it's not loaded correctly, let me know, otherwise check if it's working correctly.

Unfortunately, your custom script is based on implementation details and it's not covered by the library.

(alternative : try resetting the token, maybe it's just the cookie missing)

**Comment by sommmen** [comment]
I'm note entirely sure but i just rechecked and it seems to be working, could be because it was using a beta package, or an older package was used elsewhere - my fault.
