### ISSUE TITLE
Local requests are not allowed by default

### ISSUE THREAD

**Issue by mo-esmp** [serilog-contrib/serilog-ui#152]
Based on documentation, local requests should be allowed on a local environment:
> [By default, serilog-ui allows access to the log page only for local requests. To give appropriate rights for production use, you need to configure authorization](https://github.com/serilog-contrib/serilog-ui/wiki/%5Bv2%5D-Install:-Configuration-Options#authorization)

But it's not working if `AddScopedAuthorizeLocalRequestsAuthFilter` is not registered. 
```csharp
.AddSerilogUi(options => {
    options.AddScopedAuthorizeLocalRequestsAuthFilter();
   ...
}
```
Is my assumption correct? If yes, let's update the wiki.

**Comment by followynne** [comment]
@mo-esmp 

you're reading v2 documentation, which is correct as it is.

For v3/latest, the correct page is: https://github.com/serilog-contrib/serilog-ui/wiki/Configure#authorization
