### ISSUE TITLE
Level "Critical" not supported

### ISSUE THREAD

**Issue by E4est** [serilog-contrib/serilog-ui#29]
I can't filter my logs by Level "Critical".
When I add a critical entry, no level is displayed for the entry.

![image](https://user-images.githubusercontent.com/1894907/168055855-57781f5e-ccf4-4119-b616-9739e7840e9f.png)

**Comment by mo-esmp** [comment]
Thanks for reporting this. 

@followynne we forgot log lever [Critical](https://github.com/mo-esmp/serilog-ui/blob/f2936c8d4912b6b115c124668be95c976bbe1ccb/src/Serilog.Ui.Web/assets/types/types.ts#L25). Do you have time to fix this?

**Comment by followynne** [comment]
@mo-esmp yes, I'll try to give it a look asap this weekend 👍

**Comment by mo-esmp** [comment]
@E4est Could you please upgrade Serilog.UI package to 2.1.2-beta version and check it.

**Comment by E4est** [comment]
Hello,

I came back from my vacation and just had the chance to test it.
Now I'm realizing that my initial issue was described poorly.

On 2.1.2 it still looks like this:
![image](https://user-images.githubusercontent.com/1894907/172341489-6499dfe1-2138-46b9-86a7-472a60fb3754.png)

but apparently there is a white text in a white box saying "Fatal".
![image](https://user-images.githubusercontent.com/1894907/172347685-36860a41-7dc5-46fe-99a5-f0ef5178ce10.png)

It seems like Serilog saves critical logs as "Fatal".

(I'm using the MsSqlServerProvider, if that's relevant.)

**Comment by followynne** [comment]
Hey @E4est
Thanks for reporting back.
Can you please attach the sample log you're using in the screenshot? (json, text, as you prefer...) 

I'll use it to test more in depth the feat. 😊

**Comment by E4est** [comment]
Sure :)

```json
// The JSON payload for the screenshot.
{
    "level": "critical",
    "messageTemplate": "I hope critical works now. {Remark}",
    "properties": [
        "That would be so cool."
    ]
}
```

```c#
// The model posted to the log API.
public class LogModel
{
    public string? MessageTemplate { get; set; }

    public string? Level { get; set; }

    public ICollection<object> Properties { get; set; } = new List<object>();
}

// The API controller receiving logs.
[Route("")]
[ApiController]
public class LoggerController : ControllerBase
{
    private readonly ILogger _logger;

    public LoggerController(ILogger<LoggerController> logger)
    {
        _logger = logger;
    }

    [HttpPost("")]
    public IActionResult Insert(LogModel model)
    {
        switch (model.Level?.ToUpperInvariant())
        {
            case "CRITICAL":
                _logger.LogCritical(model.MessageTemplate, model.Properties.ToArray());
                break;
            case "DEBUG":
                _logger.LogDebug(model.MessageTemplate, model.Properties.ToArray());
                break;
            case "ERROR":
                _logger.LogError(model.MessageTemplate, model.Properties.ToArray());
                break;
            case "TRACE":
                _logger.LogTrace(model.MessageTemplate, model.Properties.ToArray());
                break;
            case "WARNING":
                _logger.LogWarning(model.MessageTemplate, model.Properties.ToArray());
                break;
            default:
                LogInvalidModel(model);
                return UnprocessableEntity("invalid level");
        }

        return NoContent();
    }

    private void LogInvalidModel(LogModel model)
    {
        _logger.LogError(
            "Invalid log model. Received: '{Request}'.",
            JsonConvert.SerializeObject(model));
    }
}
```

**Comment by followynne** [comment]
@E4est
Thanks a lot, I'm not sure when I'll be able to take a look at it but I'll try to do it asap, I'll keep you posted 😊
