### ISSUE TITLE
Would you change System.SqlData.SqlClient to Microsoft.SqlData.SqlClient

### ISSUE THREAD

**Issue by IstvanSafar** [serilog-contrib/serilog-ui#3]

**Comment by mo-esmp** [comment]
Sure I will replace  `System.SqlData.SqlClient` with `Microsoft.SqlData.SqlClient`.

**Comment by mo-esmp** [comment]
Please upgrade [Serilog.Ui.MsSqlServerProvider](https://www.nuget.org/packages/Serilog.Ui.MsSqlServerProvider/1.0.6) to version `1.0.6`.
