### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by ghost** [serilog-contrib/serilog-ui#32]
Hi,
it's SQLite support considered in a near future?

I could consider trying a PR if necessary.

Thank you!

**Comment by sommmen** [comment]
> Hi, it's SQLite support considered in a near future?
> 
> I could consider trying a PR if necessary.
> 
> Thank you!

The og authors will likely respond in due time, but you can just dupe any of the data provider projects and implement this yourself. A PR will likely go through without issue.  So I'd just go ahead and get coding because this would maybe take an hour to implement

**Comment by mo-esmp** [comment]
Hey @almait-feder, You can start implementing SQL Provider and I guess it won't take much time, please take a look at the SQL Server data provider. If you had any questions or need any help, please let us know.

**Comment by ghost** [comment]
Sorry for the late reply, I'm working on the PR on my free time.
I think I've encountered a problem.
The [SQLite sink](https://github.com/saleem-mirza/serilog-sinks-sqlite) don't store the message, [only  the message_template](https://github.com/saleem-mirza/serilog-sinks-sqlite/blob/436ee3bbf196c50c73e445a9f82d7fd63d894d10/src/Serilog.Sinks.SQLite/Sinks/SQLite/SQLiteSink.cs#L278) here calld `RenderedMessage`.
This means the format should be done in SQL or at runtime.
I don't think I'm capable of writing such SQL but the other option comes with worse performance and more custom code than the other `IDataProvider`s.
Any advice?

**Comment by mo-esmp** [comment]
I will check and let you know.

**Comment by ghost** [comment]
I've looked deeper into the SQLite sink source code and I ended up removing it from my project.
There were too many missing pieces.
As of right now I don't think it should be supported by your library, so I would close the issue.

What do you think?

**Comment by mo-esmp** [comment]
TBH, I haven't used the SQL Lite sink and If you think the sink is incomplete, then you can close otherwise adding SQL Lite doesn't take too much time.

**Comment by ghost** [comment]
Ok, I'll close this issue.

Thank you!
