### ISSUE TITLE
Ability to enable/disable authentication

### ISSUE THREAD

**Issue by jorgevp** [serilog-contrib/serilog-ui#42]
I'm using the serilog ui in an isolated container that does not use the authorization and identity provider from the httpcontext. Since by design my service cannot use an account I would like to enable/disable the authentication in the ui when declaring the Authorization Options when declaring the Serilog UI service. I will submit a PR for this issue.

**Comment by mo-esmp** [comment]
Please upgrade to version `2.2.1`.
