### ISSUE TITLE
Bug? js file does not load

### ISSUE THREAD

**Issue by sommmen** [serilog-contrib/serilog-ui#55]
Serilog no longer loads issues for me and i'm seeing the following error in the browser:

```
GET https://[REDACTED]/serilog-ui/index.6bbf471b.js net::ERR_ABORTED 404
```

Any clues what is going on?

**Comment by mo-esmp** [comment]
@sommmen thanks for reporting that. I will look into it.

**Comment by mo-esmp** [comment]
Please upgrade to version `2.2.3`.

**Comment by sommmen** [comment]
> Please upgrade to version `2.2.3`.

Works like a charm again, thanks!
