### ISSUE TITLE
Add date range filter

### ISSUE THREAD

**Issue by ricardodemauro** [serilog-contrib/serilog-ui#7]
Would be good if provided some date range filter (between this and that date).

Thanks

**Comment by mo-esmp** [comment]
Sure I will add date filter however it will be time-consuming owing to implementing the filter across all log data providers.

**Comment by ricardodemauro** [comment]
I'll implement on the log providers if you like.

Can you take care of the UI?

I'm thinking on two fields (start date + time and end date + time). what od you think?

**Comment by mo-esmp** [comment]
Thank you @ricardodemauro, I've added initial codes for the date range filter. Please check out the dev branch. I will finish the required JS codes tomorrow.

**Comment by ricardodemauro** [comment]
Alright. I`ll do some coding during the weekend.

**Comment by mo-esmp** [comment]
@ricardodemauro  could you please review [this commit](https://github.com/mo-esmp/serilog-ui/commit/d1ac016abeb82f3577d0f0cd9b26a690b37e082a). I've added the date filter but act like `OR` clause instead of `AND` clause.

**Comment by mo-esmp** [comment]
Please upgrade to version 2.1.0.
