### ISSUE TITLE
Please add support for highlight.js to show stacktrace pop up

### ISSUE THREAD

**Issue by hardcoderz** [serilog-contrib/serilog-ui#8]
Hi, great library you have created so thank you for that!
Please can you add support for https://highlightjs.org/ to show stack trace info?
It will make the stack trace more readable.

**Comment by mo-esmp** [comment]
Hi @hardcoderz 

Thanks for your suggestion. I'll take a look at  https://highlightjs.org/ and see how to integrate with the UI project.

**Comment by mo-esmp** [comment]
I used `netStack.js` rather than `highlight.js`. Please upgrade to version 2.0.1.
