### ISSUE TITLE
Error on DateTime format

### ISSUE THREAD

**Issue by arrio89** [serilog-contrib/serilog-ui#84]
the date formatter in JS have some error and show bad date time. 
![2023-07-24_15-32](https://github.com/serilog-contrib/serilog-ui/assets/1151889/7ba6a79d-dde2-4208-bf85-1bace7c949a0)

**Comment by mo-esmp** [comment]
@arrio89 What data provider are you using?
@followynne Could you please check if in frontend time is converted to UTC?

**Comment by followynne** [comment]
Hello @mo-esmp 😊

I gave a quick check, we're using [this fN from date-fns](https://date-fns.org/v2.30.0/docs/parseJSON#returns) that outputs the date in local timezone (I think it's better for the end user).

We can review and define a specific behavior for dates in the updated ui app 😊

@arrio89 can you kindly provide more info on what errors did you find? I don't notice them in the screenshot.

**Comment by mo-esmp** [comment]
@followynne the returned time from the server is `15:30:34` but the UI shows `12:30:34`. According to [this issue](https://github.com/serilog/serilog/issues/1419), Serilog uses the `DateTimeOffset` to store dates.

**Comment by followynne** [comment]
@mo-esmp

I think it's the expected behavior (we show date converted to local time).

@arrio89 can you please confirm us if you're in a -3 hrs TZ, compared to UTC?

**Comment by arrio89** [comment]
Hey Everyone,

the bug is that de UI show different hour compared with de returned by server, i mark in the screenshot this difference.
My PC is in Time zone in Buenos Aires (GMT-3).

**Comment by followynne** [comment]
Hi @arrio89,

Thanks for the feedback! 

The current behavior is to show the date and time converted in local user time ; on the server you store an UTC date while in app you'll see it with -3 hrs offset (as per your timezone).
