### ISSUE TITLE
Npgsql DateTime filtering problem 

### ISSUE THREAD

**Issue by Millarex** [serilog-contrib/serilog-ui#85]
Hi.
I use NpgSql 7.0.2 with Postgres 14, DotNet 7 
While sort by TimeStamp i had error:
![photo_2023-08-23_14-55-23](https://github.com/serilog-contrib/serilog-ui/assets/55946676/1c80caa8-fbae-4fc8-b4d4-01aae425cf74)

NpgSql > 6.0.0 have dateTime  breaking changes:
![image](https://github.com/serilog-contrib/serilog-ui/assets/55946676/b627587b-054a-44a9-a484-33a584bc128e)

I think adding a parameter to the incoming date UTS should solve the error that occurs. 
Like: DateTime.SpecifyKind(entryDateTimeValue, DateTimeKind.Utc);

**Comment by mo-esmp** [comment]
Which version of `Serilog.Sinks.Postgresql` are you using?

**Comment by Millarex** [comment]
Serilog.Sinks.Postgresql.Alternative 3.5.0 (https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative)
Serilog.UI.PostgreSqlProvider 2.2.0
