### ISSUE TITLE
Insert log test data through sinks

### ISSUE THREAD

**Issue by mo-esmp** [serilog-contrib/serilog-ui#86]
Hence, reading log data from log data providers is dependent on log table schema; we should insert log data through sinks and not directly into the database. @followynne What do you think of this?

**Comment by followynne** [comment]
Hello @mo-esmp 

I agree 100% with you, the issue I found on this topic was inserting data in a "managed" way to be able to test some filters... 
The filter that's difficult to test with this approach would be the time range one - I don't think the ILogger interface let us insert logs with a certain timestamp.

On Elastic Search I used the serilog-sink approach, if you want to [check](https://github.com/serilog-contrib/serilog-ui/blob/master/tests/Serilog.Ui.ElasticSearchProvider.Tests/Util/ElasticTestProvider.cs#L63) 😄
