### ISSUE TITLE
Using options.Authorization.AuthenticationType = AuthenticationType.Jwt; in api project 

### ISSUE THREAD

**Issue by satsvelke** [serilog-contrib/serilog-ui#91]
how this works in api project where its does not have login

**Comment by mo-esmp** [comment]
If your API has bearer token authentication, then you can enter your token in the Log Dashboard, just like in Swagger UI. Please read [Authorization](https://github.com/serilog-contrib/serilog-ui/wiki/Install:-Configuration-Options#authorization) section for more info.

![image](https://github.com/serilog-contrib/serilog-ui/assets/1659032/3c08ce8c-3d77-40c9-94f5-3eb7ffd8a9f6)

**Comment by satsvelke** [comment]
when I return false it does not show this page, I little confused how to implement the Authorize filter

**Comment by mo-esmp** [comment]
@satsvelke Could you please explain or share some codes what you want to implement?

@followynne a question: if the user is not authorized, do we show the dashboard? (the user should be able to see the dashboard to enter the JWT token)

**Comment by satsvelke** [comment]
configurations 

`app.UseSerilogUi(o =>
{
    o.Authorization.AuthenticationType = AuthenticationType.Jwt;
    o.Authorization.Filters = new[]
       {
            new SerilogAuthFilter()
        };
    o.RoutePrefix = "error-logs";
});`


My auth filter 

`  public class SerilogAuthFilter : IUiAuthorizationFilter
  {
      public bool Authorize(HttpContext httpContext)
      {
          // Allow all authenticated users to see the Dashboard (potentially dangerous).
          var key = httpContext.Request.Headers["Authorization"];

          var appSettingsJson = File.ReadAllText("appsettings.json");
          
          var appSettings = JsonConvert.DeserializeObject<dynamic>(appSettingsJson);

          if(appSettings.ErrorLogKey == key) return true;

          return false;
      }
  }`
  
  I am returning tru if the errologkey equals key , else its false but when I do that I get the below 
  
  
  
![image](https://github.com/serilog-contrib/serilog-ui/assets/17031542/e9cd4c30-65d8-4567-889d-8a4b84119152)

If I return true I can see the logs without auth

**Comment by followynne** [comment]
Hello @mo-esmp

In the current impl user is authorized only against endpoints, not when accessing index, thus it should work fine.

I think that the 1st impl of the Auth filter was requesting authorization on index - I remember it because in sample there was a commented part to remove the filters registration, otherwise you would get 403 on /index... 

@satsvelke can you tell us the package version you're using?
If you inspect the headers property, is your expected key found?

**Comment by satsvelke** [comment]
I am using 2.4.0, and also I am not getting async verion of IUiAsyncAuthorizationFilter

**Comment by mo-esmp** [comment]
@satsvelke We recently added `IUiAsyncAuthorizationFilter` but the new version of the package has not been published yet  (sorry, my bad).
>If I return true I can see the logs without auth

You should return `true` when you checked all necessary things to check if a user can access the dashboard or not, i.e., the user is authenticated and the provided key is correct.
```csharp
{
public class CustomAuthorizeFilter : IUiAuthorizationFilter
{
    public bool Authorize(HttpContext httpContext)
    {
        // Check if user is authenticated
        if(httpContext.User.Identity is { IsAuthenticated: false})
        {
            return false;
        }
        
        // Check if the KEY is correct
        var key = httpContext.Request.Headers["Authorization"];
        var appSettingsJson = File.ReadAllText("appsettings.json");
        var appSettings = JsonConvert.DeserializeObject<dynamic>(appSettingsJson);

        return appSettings.ErrorLogKey == key;
    }
}
```

 It's up to you how you want to check if a user can access the dashboard or not.

**Comment by followynne** [comment]
@mo-esmp

FYI, I'll try to run a quick test on 2.4 those days to see if the index can be accessed with Auth enabled and comment back here 😊

**Comment by satsvelke** [comment]
thanks 👍

**Comment by followynne** [comment]
@mo-esmp 

tried with 2.4.0 and /index can't be reached if
- you enable authentication filters 
- the authentication depends on the ui page (ex: when you send the token from there)

I think you can release the new version and mark 2.4.0 as deprecated on Nuget 👍 

(I'll keep this thread in mind for the new ui, with an additional parameter to block /index only if the end-user does so in the setup etc...)

**Comment by satsvelke** [comment]
can I know when will be the new version releasing?

**Comment by mo-esmp** [comment]
I just published new packages; sorry for the delay.

**Comment by satsvelke** [comment]
thanks , this works perfectly
