### ISSUE TITLE
When I am using MongoDb Sink provider Exception and properties column not populating in serilog.Ui

### ISSUE THREAD

**Issue by vivekbajpai4284** [serilog-contrib/serilog-ui#94]
I configured MongoDB BSON Sink for logging details in a MongoDB database, and  I can see the properties  and Exception fields inside the collection with the exact exception which I am getting from the service, but Serilog.UI cannot bind the exception and property columns in the Serilog.UI grid.

I debugged the Serilog.UI.MongoDbProvider, and I tested the same code in my local repository. I observed that in the MongoDbDataProvider.cs class, the logs are not getting the exception and properties from the collection.

I'm not sure, but maybe I need to format the data while sinking. Can anyone please help me out with this issue?

I used the same code from  Serilog.UI.MongoDbProvider for testing I got the result but with Exception field
![IMG-0007](https://github.com/serilog-contrib/serilog-ui/assets/74507671/16b0eb86-5f3d-4345-8f70-b77096258a7e)

**Comment by mo-esmp** [comment]
For MongoDB, logs are deserialized to the [MongoDbLogModel](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.MongoDbProvider/MongoDbLogModel.cs) class, and properties are based on the [Serilog.Sinks.MongoDB](https://github.com/ChangemakerStudios/serilog-sinks-mongodb#-serilogsinksmongodb) collection. If your collection is different from the mentioned sink, it cannot read the data properly,and if both are the same, please share some codes with us to reproduce the bug.

**Comment by vivekbajpai4284** [comment]
I'm using the same collection [Serilog.Sinks.MongoDB](https://github.com/ChangemakerStudios/serilog-sinks-mongodb#-serilogsinksmongodb) from this collection I'm using MongoDbBason method Initialize the collection name with all necessary configuration. 
Program.cs 
```csharp
var logger = new LoggerConfiguration().ReadFrom.Configuration(builder.Configuration)
    .Enrich.FromLogContext()
    .Enrich.WithExceptionDetails()
    .WriteTo.MongoDBBson(
        cfg =>
        {
            cfg.SetMongoUrl(MongoDbConnString);
            // optional configuration options:
            cfg.SetCollectionName("storageControllerLogs");
            cfg.SetExpireTTL(TimeSpan.FromDays(30));
        }
    )
    .CreateLogger();
//To Clear the default log provider
builder.Logging.ClearProviders();
builder.Logging.AddSerilog(logger);

// Handle unhandled exceptions
AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
// Handle graceful shutdown
AppDomain.CurrentDomain.ProcessExit += (s, e) =>
{
    Log.Information("Application is shutting down.");
    Log.CloseAndFlush();
};
````

For  the UI 
```csharp
private static void RegisterAddSerilogUi(this IServiceCollection services)
        {
            // Register the Serilog UI services
            services.AddSerilogUi(options => options.UseMongoDb(MongoDbConnString, "storageControllerLogs"));
        }
```

**Comment by mo-esmp** [comment]
@vivekbajpai4284 Could you please update `Serilog.Ui.MongoDbProvider` to the latest version and let me know if the problem still exists?

**Comment by mo-esmp** [comment]
Feel free to re-open the issue if it is still not resolved.

**Comment by vivekbajpai4284** [comment]
Hi Mohsen,

I have checked with the new package Serilog.UI.MongoDbProvider (version 2.3.1), but the UI still does not display the stack trace. I verified in the MongoDB database that we do have a stack trace, but the UI's Exception column remains blank; there is nothing displayed there.
![IMG_0189](https://github.com/serilog-contrib/serilog-ui/assets/74507671/185f732e-e968-4868-bd59-0d6b356e1902)
![IMG_0188](https://github.com/serilog-contrib/serilog-ui/assets/74507671/dc3d68f7-f164-4789-9f22-f28ae6be21e2)

**Comment by mo-esmp** [comment]
Hey @vivekbajpai4284,
Please use the browser Development Tools -> Network tab and you should find calls to an `/logs` endpoint and check if a stack trace (`Error` property) is returned from the server or not.

**Comment by mo-esmp** [comment]
Hey @vivekbajpai4284,
Please use the browser Development Tools -> Network tab and you should find calls to an `/logs` endpoint and check if a stack trace is returned from the server or not.

**Comment by followynne** [comment]
Hello @vivekbajpai4284 

can you kindly retest your issue with the latest version? (v3)

**Comment by followynne** [comment]
Closed for inactivity.
