### ISSUE TITLE
XML output isn't rendered correctly

### ISSUE THREAD

**Issue by GuidoNeele** [serilog-contrib/serilog-ui#99]
**Describe the bug**
Opening the properties details view multiple times does funny things to rendered xml. `<test>` becomes `&lt;test&gt;`, closing and opening another time will produce `&amp;lt;test&amp;gt;`

**To Reproduce**
1. Go to dashboard
2. Click on 'View'
3. Close dialog
4. Click on 'View' again
5. See < being converted to &lt;

**Expected behavior**
The details dialog should show xml tags.

**Screenshots**
![image](https://github.com/serilog-contrib/serilog-ui/assets/1301586/2bec5c62-0dd6-4c86-b69b-526155430faf)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 120

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mo-esmp** [comment]
Thanks for reporting the issue, and sorry for replying late. I will check soon once I return from vacation.

**Comment by mo-esmp** [comment]
@followynne Do you have time to check on this issue?

**Comment by followynne** [comment]
@mo-esmp

I'll try to take a look at it this week 😊
